### ISSUE TITLE
Colors are not rendered in the PDF report with puppeteer

### ISSUE THREAD

**Issue by jniles** [third-culture-software/bhima#4382]
I'm not sure why colors are not being rendered on puppeteer.  Here is the "analyse de caisse auxiliares" report:

![image](https://user-images.githubusercontent.com/896472/80478568-98f28200-8945-11ea-8f18-af9004ae570b.png)
_Fig 1: PDF version of the caisse auxiliares report_

Normally, these icons have colors behind them.  It should look like this:
![image](https://user-images.githubusercontent.com/896472/80479400-df94ac00-8946-11ea-9e39-1f2ca1f3ec4a.png)

Someone should investigate this and correct this issue.

**Comment by jeremielodi** [comment]
Still investigating. This bellow code works perfectly.
```js



const pptr = require('puppeteer');

async function render() {
  const pptrOptions = {
    headless : true,
    args : [
      '--bwsi',
      '--disable-default-apps',
      '--disable-dev-shm-usage',
      '--disable-setuid-sandbox',
      '--hide-scrollbars',
      '--disable-web-security',
      '--no-sandbox',
    ],
  };

  const html = `<div style='width: 100%; font-size:12px; color:white; background:black; -webkit-print-color-adjust:exact'>Cool</div>`;
  
  let browser = await pptr.launch(pptrOptions);
  
  const page = await browser.newPage();
  page.setContent(html);
  const pdf = await page.pdf({
    margin: { top: "40", bottom: "40" },
    printBackground: true,
    path: 'bg.pdf',
    format: 'A4',
  });
  await browser.close();
}

render();

```

**Comment by jeremielodi** [comment]
The main problem comes from our css. until now I don't know where exactily

When I try to remove it link from the handlebars

```html
<html>
  
  <meta charset="utf-8"/>
  <title>{{translate 'REPORT.ANALYSIS_AUX_CASHBOXES.TITLE' }}</title>

  <body>
    <div style="margin-right: 2%; margin-left: 2%;">
      {{> header}}

```
I have this result as pdf


![pdf1](https://user-images.githubusercontent.com/25838121/81190554-e1e2b000-8faf-11ea-9200-f6f82b48bd17.PNG)

**Comment by jeremielodi** [comment]
We specified this in one of our css files
```css
/*! Source: https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css */
@media print {
  *,
  *:before,
  *:after {
    color: #000 !important;
    text-shadow: none !important;
    background: transparent !important;
    box-shadow: none !important;
  }

```
